[DIR]
arvi = E:\ADM IRC AND ZN\ARVIEWER.xlsm
arvi_ar_sheet = Source
arvi_name_out = Nama Pelanggan SS
arvi_pay_sales = Pembayaran SS
ml_trainning = E:\ADM IRC AND ZN\AR Pusat Machine Learning\ML\Hasil_Latihan_temp.xlsx

[MAP]
depo = SL|YY|MKS|MGL|PW|PWT|PLU|SG|SMG|TGL|PA|KDI

[GROUP_KEYWORDS]
manis = manis
depo = manis

[BRANCH_RULES]
sumo|godong = CV. SUMO SUKSES SENTOSA GODONG
sumo|purwodadi = CV. SUMO SUKSES SENTOSA

[AUTH]
secret_key = 

[BOT]
bot_token = 

[FBACK]
url = 

[GENERAL]
gen_company_name = 
